backend:
  name: git-gateway
  branch: main

# local_backend: true

# publish_mode: editorial_workflow

editor:
  preview: false

display_url: https://neilgames.netlify.app
media_folder: 'public/media'
public_folder: '/media'

collections:
  - name: 'page'
    label: 'Pages'
    files:
      - file: 'content/page/home.md'
        label: 'Home'
        name: 'home'
        fields:
          - label: 'Title'
            name: 'title'
            widget: string

      - file: 'content/page/about.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
              label: 'Description',
              name: 'description',
              widget: 'markdown',
              sanitize_preview: true,
              buttons: ['bold', 'italic', 'link'],
              modes: ['rich_text'],
              editor_components: ['iframe'],
            }

      - file: 'content/page/contact.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }

  - name: 'wordle-games' # Used in routes, e.g., /admin/collections/blog
    label: 'Wordle Games' # Used in the UI
    folder: 'content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{title}}' # Filename template, e.g., 2024-090-25-name-of-doc.md
    view_groups:
      - label: Category
        field: categories
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog',
        }
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Featured', name: 'featured', widget: boolean, default: false }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'select',
          options: ['Wordle Games', 'Fun Game', 'Old games', 'spend money game', 'dinosaur-games'],
          multiple: false,
          required: true
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          sanitize_preview: true,
          modes: ['rich_text'],
          buttons: ['bold', 'italic', 'link', 'code'],
          editor_components: ['iframe'],
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

  - name: 'fun-game'
    label: 'Fun Game'
    folder: 'content/inspiration'
    create: true
    slug: '{{title}}'
    extension: mdx
    format: frontmatter
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'inspiration',
        }
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Featured', name: 'featured', widget: boolean, default: false }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          choose_url: false,
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          sanitize_preview: true,
          minimal: true,
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

  - name: 'old-games'
    label: 'Old Games'
    label_singular: 'Old Games'
    folder: 'content/podcasts'
    create: true
    slug: '{{title}}'
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'podcasts',
        }
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Featured', name: 'featured', widget: boolean, default: false }
      - { label: 'Link', name: 'link', widget: string }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          choose_url: false,
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          sanitize_preview: true,
          minimal: true,
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

  - name: 'tools'
    label: 'Tools'
    label_singular: 'Tool'
    folder: 'content/tools'
    create: true
    slug: '{{title}}'
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'tools',
        }
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Featured', name: 'featured', widget: boolean, default: false }
      - {
          label: 'App Icon Image',
          name: 'image',
          widget: 'image',
          choose_url: false,
        }
      - { label: 'Link', name: 'link', widget: string }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          sanitize_preview: true,
          minimal: true,
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

  - name: 'spend-money-game'
    label: 'Spend Money Game'
    label_singular: 'Spend Games'
    folder: 'content/resources'
    create: true
    slug: '{{title}}'
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'resources',
        }
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Featured', name: 'featured', widget: boolean, default: false }
      - { label: 'Image', name: 'image', widget: 'image', choose_url: false }
      - { label: 'Link', name: 'link', widget: string }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          sanitize_preview: true,
          minimal: true,
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }

editor_components:
  - label: Iframe
    id: iframe
    widget: object
    fields:
      - { label: 'URL', name: 'src', widget: 'string' }
      - { label: 'Height', name: 'height', widget: 'string', default: '400' }
      - { label: 'Width', name: 'width', widget: 'string', default: '100%' }
    pattern: '{{< iframe src="{{src}}" height="{{height}}" width="{{width}}" >}}'
    from_block: |
      ^{{<\s*iframe\s+src="(?P<src>[^"]+)"\s+height="(?P<height>[^"]+)"\s+width="(?P<width>[^"]+)"\s*>}}$
    to_block: |
      {{< iframe src="{{src}}" height="{{height}}" width="{{width}}" >}}

  # - name: 'authors'
  #   label: 'Authors'
  #   folder: 'content/authors'
  #   create: true
  #   slug: '{{name}}'
  #   fields:
  #     - { label: 'Name', name: 'name', widget: 'string', required: true }
  #     - {
  #         label: 'About',
  #         name: 'description',
  #         widget: 'markdown',
  #         sanitize_preview: true,
  #         buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three'],
  #         modes: ['rich_text'],
  #         editor_components: [''],
  #       }
  #     - {
  #         label: 'Featured Image',
  #         name: 'image',
  #         widget: 'image',
  #         choose_url: false,
  #       }
